export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILED = "GET_DATA_FAILED";


export const GET_DATA_LIKED = "GET_DATA_LIKED";
export const ADD_DATA_LIKED = "ADD_DATA_LIKED";
export const REMOVE_DATA_LIKED = "REMOVE_DATA_LIKED";